### ISSUE TITLE
mail 설정 시 tls로 설정했는데 ssl오류가 남

### ISSUE THREAD

**Issue by suyeonkwong** [E-TF/Fresh-place#28]
```
mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(OAUQ7tJ/g5WUVgih8SQWdRXt8Ml7dgVWKxR9m3OnPEY=)
    password: ENC(PONAUmQrQ4JhiO3cqu38LbWOnp85Vq3SEUq3xTYgQt0=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
```

```
2022-11-24 19:44:19.168 ERROR 40504 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587;
  nested exception is:
	javax.net.ssl.SSLException: Unsupported or unrecognized SSL message. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587;
  nested exception is:
	et.ssl.SSLException: Unsupported or unrecognized SSL message; message exceptions (1) are:
Failed message 1: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587;
  nested exception is:
	javax.net.ssl.SSLException: Unsupported or unrecognized SSL message] with root cause

javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

 + 원인 : google에서 mail 서비스 수준낮은 보안 정책을 2022년 5월 30일부터 중지 시켰다. 
 + 해결 : 앱 비밀번호를 발급받아 사용해야 하는데 

 + 문제2 : 다른 문제는 MailSender 인터페이스를 DI하지 않고 JavaMailSender구현체를 DI했는데 계속 bean오류가 났고 bean을 override설정 해줬는데도 메일 전송이 되지 않았다. spring boot에서 
```
implementation 'org.springframework.boot:spring-boot-starter-mail'
```
 설정해주면 JavaMailSender를 빈등록하지 않아도 사용할 수 있다고 나왔는데 나는 계속 빈 오류가 났고 overide설정해주라는게 이미 빈이 생성되어있다는 의미라서 properties파일을 계속 찾아보았는데 내부적으로 JavaMailSneder를 주입하고 있었고 properties설정에서 AutoConfiguration덕분에 호스트나 포트나 비밀번호를 다 설정해줬다. 나는 그것도 모르고 bean등록하고 properties설정을 일일이 해줘서 같은 bean 이 겹치는 문제가 생겼다. 스프링이 내부적으로 너무 AutoConfiguration을 잘해주니까 오히려 이런문제가 생겼다 ;; 

 + 해결 : 
![캡처](https://user-images.githubusercontent.com/80368511/203779391-a5cf8572-1005-43d6-904d-584fc3b42421.PNG)

메일 전송을 완료했다.
